[package]
name = "example_stm32f4"
version = "0.4.0"
edition = "2021"

[profile.release]
panic = "abort"
debug = true

[dependencies]
# Specifying Martos version
# martos = "0.4.0"
# Specifying current Martos version path for ci
martos = { path = "../../../../", features = ["cortex_m"] }
cortex-m-rt = "0.7"
# cortex-m-semihosting = "0.5" for debug in QEMU
